const winterCrops = [
    "Winterbor Kale",
    "Tuscan Kale",
    "Siberian Kale",
    "Curly Parsley",
    "Flat Leaf Parsley",
    "Garlic Chives",
    "Winter Thyme",
    "Common Sage",
    "Purple Sage",
    "Tuscan Blue Rosemary",
    "Bay Laurel",
    "Hollow Crown Parsnip",
    "Harris Model Parsnip",
    "Rutabaga",
    "Laurentian Rutabaga",
    "American Purple Top Rutabaga",
    "Purple Top Turnip",
    "Hakurei Turnip",
    "Golden Globe Turnip",
    "Brilliant Celeriac",
    "Giant Prague Celeriac",
    "Long White Icicle Radish",
    "Black Spanish Radish",
    "Winter Radish",
    "Long Island Improved Sprouts",
    "Red Delicious Sprouts",
    "January King Cabbage",
    "Stonehead Cabbage",
    "Giant Red Mustard",
    "Winter Purslane",
    "Winter Arugula",
    "Chioggia Radicchio",
    "Treviso Radicchio",
    "Winter Giant Spinach",
    "Bloomsdale Spinach",
    "Georgia Southern Collards",
    "Vates Collards",
    "King Richard Leeks",
    "Giant Musselburgh Leeks",
    "Grey Shallots",
    "Banana Shallots",
    "Winter Garlic",
    "Hardneck Garlic",
    "Softneck Garlic",
    "Storage Onion",
    "Patience Dock",
    "French Sorrel",
    "Sunchoke",
    "Winter Squashes (Stored)",
    "Butternut Squash (Stored)",
    "Acorn Squash (Stored)",
    "Hubbard Squash (Stored)",
    "Pumpkins (Stored)",
    "Sugar Pie Pumpkin (Stored)",
    "Sweet Potato (Cured)",
    "Yam (Cured)",
    "Cylindra Beet",
    "Detroit Dark Red Beet",
    "Golden Beet",
    "Chioggia Beet",
    "Early Purple Vienna Kohlrabi",
    "Superschmelz Kohlrabi",
    "Purple Sprouting Broccoli",
    "Winter Cauliflower",
    "Romanesco",
    "Sugar Peas (Winter)",
    "Snow Peas (Winter)",
    "Fava Beans (Winter)",
    "Broad Beans (Winter)",
    "Black Beans (Dried)",
    "Kidney Beans (Dried)",
    "Pinto Beans (Dried)",
    "Navy Beans (Dried)",
    "Great Northern Beans (Dried)",
    "Green Lentils",
    "Red Lentils",
    "Black Lentils",
    "Wonderful Pomegranate",
    "Kiwifruit",
    "Hardy Kiwi",
    "Citrus",
    "Navel Orange",
    "Blood Orange",
    "Cara Cara Orange",
    "Seville Orange",
    "Meyer Lemon",
    "Eureka Lemon",
    "Lisbon Lemon",
    "Key Lime",
    "Persian Lime",
    "Ruby Red Grapefruit",
    "Marsh Grapefruit",
    "Clementine",
    "Mandarin",
    "Satsuma Mandarin",
    "Nagami Kumquat",
    "Meiwa Kumquat",
    "Pomelo",
    "Buddha's Hand",
    "Yuzu",
    "Finger Lime",
    "Shiitake Mushroom",
    "Enoki Mushroom",
    "Maitake Mushroom",
    "Wood Ear Mushroom",
    "Dried Corn",
    "English Walnut",
    "Black Walnut",
    "Filberts",
    "American Chestnut",
    "Chinese Chestnut",
    "Sprouted Grains",
    "Chickweed",
    "Mountain Spinach",
    "Giant Butterhead Lettuce",
    "Winter Lettuce",
    "Lamb's Lettuce",
    "Fiddleheads (Stored/Dried)",
    "Bamboo Shoots (Canned)",
    "Artichokes (Canned)",
    "Asparagus (Canned)",
    "Sweet Corn (Canned)",
    "Green Beans (Canned)",
    "Tomatoes (Canned)",
    "Tomato Paste",
    "Tomato Puree",
    "Sundried Tomatoes",
    "Dried Chili Peppers",
    "Ancho Chili",
    "Guajillo Chili",
    "Pasilla Chili",
    "Mulato Chili",
    "Chipotles",
    "Cinnamon Sticks",
    "Black Peppercorns",
    "White Peppercorns",
    "Pink Peppercorns",
    "Sichuan Peppercorns",
    "Dried Oregano",
    "Dried Marjoram",
    "Dried Sage",
    "Dried Thyme",
    "Dried Savory",
    "Dried Rosemary",
    "Dried Mint",
    "Dried Cilantro",
    "Dried Dill",
    "Dried Parsley",
    "Dried Tarragon",
    "Dried Chervil",
    "Dried Lemon Verbena",
    "Dried Lavender",
    "Dried Chamomile",
    "Dried Calendula",
    "Dried Nasturtium",
    "Dried Cornflowers",
    "Dried Hibiscus",
    "Dried Elderflowers",
    "Dried Rose Petals",
    "Dried Raspberry Leaves",
    "Dried Strawberry Leaves",
    "Dried Blackberry Leaves",
    "Dried Nettle",
    "Dried Red Clover",
    "Dried Alfalfa",
    "Dried Peppermint",
    "Dried Spearmint",
    "Dried Hyssop",
    "Dried Lovage",
    "Dried Fennel Seeds",
    "Dried Anise Seeds",
    "Dried Caraway Seeds",
    "Dried Cumin Seeds",
    "Dried Coriander Seeds",
    "Dried Mustard Seeds",
    "Dried Celery Seeds",
    "Dried Ajwain Seeds",
    "Dried Fenugreek Seeds",
    "Dried Nigella Seeds",
    "Dried Poppy Seeds",
    "Dried Sesame Seeds",
    "Dried Sunflower Seeds",
    "Dried Pumpkin Seeds",
    "Dried Chia Seeds",
    "Dried Flax Seeds",
    "Dried Hemp Seeds",
    "Dried Squash Seeds",
    "Dried Watermelon Seeds",
    "Dried Muskmelon Seeds",
    "Dried Gourd Seeds",
    "Dried Papaya Seeds",
    "Dried Citrus Peels",
    "Dried Apple Rings",
    "Dried Apricots",
    "Dried Pears",
    "Dried Peaches",
    "Dried Plums",
    "Dried Figs",
    "Dried Dates",
    "Dried Raisins",
    "Dried Currants",
    "Dried Cranberries",
    "Dried Blueberries",
    "Dried Cherries",
    "Dried Mulberries",
    "Dried Persimmons",
    "Dried Mango",
    "Dried Pineapple"
];